# ansible/tasks/dotfiles.yml
---
- name: Stow dotfile packages
  ansible.builtin.command:
    cmd: stow --restow "{{ item }}"
    chdir: "{{ dotfiles_repo_path }}"
  become: no
  loop: "{{ stow_packages }}"
  tags: dotfiles
